name: "Auto Update"

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          token: "${{ secrets.PROTON_GE_TAR_MAKER_COMMIT_TOKEN }}"

      - name: "Fetch latest version of GloriousEggroll/proton-ge-custom"
        run: >-
          echo "LATEST_VERSION=$(
            curl -Ls https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases/latest |
            jq -r ".tag_name"
          )" >> $GITHUB_ENV

      - name: "Update tarball.yaml with latest version using yq"
        uses: "mikefarah/yq@v4.41.1"
        with:
          cmd: "yq eval -i '.env.PROTON_GE_RELEASE = \"${{ env.LATEST_VERSION }}\"' .github/workflows/tarball.yaml"

      - name: "Set release number in tarball.yaml to 1 using yq"
        uses: "mikefarah/yq@v4.41.1"
        with:
          cmd: "yq eval -i '.env.RELEASE = \"1\"' .github/workflows/tarball.yaml"

      - name: "Commit modified files"
        uses: "stefanzweifel/git-auto-commit-action@v5.0.0"
        with:
          commit_author: "autocommit[bot] <autocommit[bot]@norealmail.net>"
          commit_message: "Proton: Update to ${{ env.LATEST_VERSION }}"
          commit_user_email: "autocommit[bot]@norealmail.net>"
          commit_user_name: "autocommit[bot]"
